### ISSUE TITLE
regarding  pascal dataset 2012 groundtruth information

### ISSUE THREAD

**Issue by sreevasu** [pecarlat/caffeTools#1]
HI,

 source: "/home/pierre/pascal_2012/train_gt_lmdb"
and

source: "/home/pierre/pascal_2012/val_gt_lmdb"

I could not find tain and test ground truth information files to create lmdb file please can you help me on this.

thanking you

**Comment by pierre-ecarlat** [comment]
Hey!
LMDB is a format for image datasets, quite common in Caffe. You can download Pascal VOC 2012 on [their website](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/), and then, you will have to convert it into LMDB if you want to use it. My guess is that I used this script: "[create_dataset_lmdb.py](https://github.com/pecarlat/caffeTools/blob/master/create_dataset_lmdb.py)" to create it (because of its name), but keep in mind that I created it a while ago, that I haven't used Caffe for a while, and that this might not work easily with your environment.
If it doesn't work, check on the web, there is probably a lot of supported scripts which do that now. :)

**Comment by sreevasu** [comment]
hi pecarlat,

thank you very much for your response. The problem is in Pascal VOC 2012 dataset file contains like:
voc2012/imagesets/segmentation file contains train.txt, val.txt, trainval.txt . But i could not have groundtruth related txt files information. please can you provide or help me on these.

thanking you

**Comment by pierre-ecarlat** [comment]
Hi!
Pascal VOC (2007 to 2012) should repect the following architecture:
|-- VOC[year] / JPEGImages (all the images, xxxx.jpg)
|-- VOC[year] / Annotations (all the ground truth, xxxx.xml -> this is what you're looking for)
|-- VOC[year] / ImageSets / Main (lists of images in the sets, trainval.txt, test.txt, all.txt, etc)
All you need is in the above directories

**Comment by sreevasu** [comment]
HI,  pierre-ecarlat

Thank you very much for you response. Do you have ground truth (annotations) train, test and val txt files. 

thanking you

**Comment by pierre-ecarlat** [comment]
Hi, again, you can find them in the `VOC[year] / Annotations` directory, that you can download from Pascal VOC website (I shared it above).
